[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv", "opencv4"]

[phases.install]
cmds = [
  "python -m venv --system-site-packages .venv",
  ". .venv/bin/activate",
  "pip install --user -r requirements.txt"
]

[start]
cmd = ". .venv/bin/activate && python -m uvicorn app:app --host=0.0.0.0 --port=${PORT:-8000}"
